# Generated by Django 5.1.2 on 2024-11-18 15:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
